pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-template')
        DB_CREDS        = credentials('pgaas-lab2')
        VAULT_CREDS     = credentials('vault_lab_3')
        PROJECT_NAME    = "BigDataLab3"
        IMAGE_NAME      = "lab3"
        PG_DB    = "postgres"
        LC_ALL   = "en_US.UTF-8"
        LANG     = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Pull image') {
            steps {
                sh 'docker pull ddulaev/$IMAGE_NAME:latest'
            }
        }

        stage('Building .env file for docker compose') {
            steps {
                sh '''
                    echo VAULT_CREDS_PSW=$VAULT_CREDS_PSW > .env
                    echo PG_USER=$DB_CREDS_USR >> .env
                    echo PG_PASSWORD=$DB_CREDS_PSW >> .env
                    echo PG_DB=$PG_DB >> .env
                '''
            }
        }

        stage('Downloading docker-compose') {
            steps {
                sh 'curl https://raw.githubusercontent.com/Timoniche/$PROJECT_NAME/main/docker-compose.yml -o docker-compose.yml'
                sh 'ls'
            }
        }

        stage('Running docker compose') {
            steps {
                sh 'docker compose up -d'
                sh 'sleep 10'
                sh 'docker compose logs'
            }
        }

        stage('Running functional tests') {
            steps{
                sh 'docker compose exec web python -m src.func_tests.api_test'
            }
        }
	}

    post {
        always {
            sh 'docker compose down'
            sh 'docker logout'
            sh 'rm -f .env'
        }
    }
}
